name: Arduino compile examples
on: [push, pull_request]

# https://github.com/marketplace/actions/compile-arduino-sketches

jobs:
  arduino-compile-examples:
    name: ${{ matrix.board.fqbn }}
    runs-on: ubuntu-20.04
    timeout-minutes: 20
    strategy:
      fail-fast: false
      max-parallel: 20
      matrix:
        board:
          - fqbn: "arduino:avr:uno"
            platform-name: arduino:avr

    steps:
      - uses: actions/checkout@v2
      - name: Compiles every example with Arduino IDE.
        uses: arduino/compile-sketches@v1
        with:
          platforms: ${{ matrix.platforms }}
          fqbn: ${{ matrix.board.fqbn }}
          enable-warnings-report: true
          enable-deltas-report: true
      - uses: actions/upload-artifact@v2
        with:
          name: sketches-reports
          path: sketches-reports
