name: Arduino compile examples
on: [push, pull_request]

# https://github.com/marketplace/actions/compile-arduino-sketches

jobs:
  arduino-compile-examples:
    runs-on: ubuntu-20.04
    timeout-minutes: 20
    strategy:
      fail-fast: false
      max-parallel: 20
      matrix:
        fqbn: ['arduino:avr:uno', 'arduino:avr:mega', 'esp8266:esp8266:d1_mini']
    steps:
      - uses: actions/checkout@v2
      - name: Compiles every example with Arduino IDE.
        uses: arduino/compile-sketches@v1
        with:
          fqbn: ${{ matrix.fqbn }}
          enable-warnings-report: true
