name: Arduino compile examples
on: [push, pull_request]

# https://github.com/marketplace/actions/compile-arduino-sketches

jobs:
  arduino-compile-examples:
    runs-on: ubuntu-20.04
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v2
      - name: Compiles every example with Arduino IDE.
        uses: arduino/compile-sketches@v1
        with:
          fqbn: 'arduino:avr:uno'
          enable-warnings-report: true
